name: static analysis

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none
          extensions: dom, curl, mbstring, sqlite3, pdo_sqlite
          tools: composer:v2

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --with="illuminate/support:^12.0"

      - name: Run static analysis
        run: composer analyse
